### ISSUE TITLE
css input and button not working

### ISSUE THREAD

**Issue by Proladon** [ChrisKnott/Eel#127]
In html previewer or direct open html in browser, all widgets css works really good
![Image](https://i.imgur.com/GvL6X9G.png)

ah...but when i run in Eel app, only paragraph css works
![Image](https://i.imgur.com/ZAihbs2.png)

I'm very sure i have save the files.
and here's the code:
## PYTHON
```python
import eel

eel.init('web')
eel.start('main_1.html')
```

## HTML
```html
<!DOCTYPE html>
<html>
    <head>
        <title>EEL GUI</title>
        <link rel="stylesheet" href="style.css">
        <script type="text/javascript" src="/eel.js"></script>
        <script src="func.js"></script>
    </head>
    <body>
        <p class="color_1">Hello World</p>
        <input class="color_3" id="txt_input" type="text" placeholder="Wite anything here">
        <button class="color_2" type="submit">Okay</button>
        <button class="color_3">Button</button>
    </body>
</html>
```

## CSS
```css
p.color_1 {
    color: rgb(25, 168, 194);
    font-family: "DisposableDroid BB";
    font-size: 40px;
}

button.color_2 {
    background-color: rgb(92, 207, 211);
    border: 0px;
    height: 20px;
}

.color_3 {
    background-color: rgb(92, 207, 211);
    color: greenyellow;
}
```
